[test]
preload = ["./scripts/ensure-db-ready.ts"]

coverage = true
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "src/db/**",
  "scripts/**",
  "**/providers/**",
  "tests/helpers/**"
]